//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnforcementAction) DeepCopyInto(out *EnforcementAction) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnforcementAction.
func (in *EnforcementAction) DeepCopy() *EnforcementAction {
	if in == nil {
		return nil
	}
	out := new(EnforcementAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyEnforcement) DeepCopyInto(out *PolicyEnforcement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyEnforcement.
func (in *PolicyEnforcement) DeepCopy() *PolicyEnforcement {
	if in == nil {
		return nil
	}
	out := new(PolicyEnforcement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyEnforcement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyEnforcementList) DeepCopyInto(out *PolicyEnforcementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyEnforcement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyEnforcementList.
func (in *PolicyEnforcementList) DeepCopy() *PolicyEnforcementList {
	if in == nil {
		return nil
	}
	out := new(PolicyEnforcementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyEnforcementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyEnforcementSpec) DeepCopyInto(out *PolicyEnforcementSpec) {
	*out = *in
	out.PolicyRuleRef = in.PolicyRuleRef
	out.TargetRef = in.TargetRef
	if in.EnforcementTime != nil {
		in, out := &in.EnforcementTime, &out.EnforcementTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyEnforcementSpec.
func (in *PolicyEnforcementSpec) DeepCopy() *PolicyEnforcementSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyEnforcementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyEnforcementStatus) DeepCopyInto(out *PolicyEnforcementStatus) {
	*out = *in
	if in.ViolationsDetected != nil {
		in, out := &in.ViolationsDetected, &out.ViolationsDetected
		*out = make([]PolicyViolation, len(*in))
		copy(*out, *in)
	}
	if in.ActionsApplied != nil {
		in, out := &in.ActionsApplied, &out.ActionsApplied
		*out = make([]EnforcementAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEnforced != nil {
		in, out := &in.LastEnforced, &out.LastEnforced
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyEnforcementStatus.
func (in *PolicyEnforcementStatus) DeepCopy() *PolicyEnforcementStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyEnforcementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRule) DeepCopyInto(out *PolicyRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRule.
func (in *PolicyRule) DeepCopy() *PolicyRule {
	if in == nil {
		return nil
	}
	out := new(PolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRuleList) DeepCopyInto(out *PolicyRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRuleList.
func (in *PolicyRuleList) DeepCopy() *PolicyRuleList {
	if in == nil {
		return nil
	}
	out := new(PolicyRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRuleSpec) DeepCopyInto(out *PolicyRuleSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourcePolicies != nil {
		in, out := &in.ResourcePolicies, &out.ResourcePolicies
		*out = new(ResourcePolicies)
		(*in).DeepCopyInto(*out)
	}
	if in.ProbePolicies != nil {
		in, out := &in.ProbePolicies, &out.ProbePolicies
		*out = new(ProbePolicies)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityPolicies != nil {
		in, out := &in.SecurityPolicies, &out.SecurityPolicies
		*out = new(SecurityPolicies)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRuleSpec.
func (in *PolicyRuleSpec) DeepCopy() *PolicyRuleSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRuleStatus) DeepCopyInto(out *PolicyRuleStatus) {
	*out = *in
	if in.LastApplied != nil {
		in, out := &in.LastApplied, &out.LastApplied
		*out = (*in).DeepCopy()
	}
	if in.EnforcedNamespaces != nil {
		in, out := &in.EnforcedNamespaces, &out.EnforcedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRuleStatus.
func (in *PolicyRuleStatus) DeepCopy() *PolicyRuleStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyViolation) DeepCopyInto(out *PolicyViolation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyViolation.
func (in *PolicyViolation) DeepCopy() *PolicyViolation {
	if in == nil {
		return nil
	}
	out := new(PolicyViolation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbePolicies) DeepCopyInto(out *ProbePolicies) {
	*out = *in
	if in.DefaultLivenessProbe != nil {
		in, out := &in.DefaultLivenessProbe, &out.DefaultLivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultReadinessProbe != nil {
		in, out := &in.DefaultReadinessProbe, &out.DefaultReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbePolicies.
func (in *ProbePolicies) DeepCopy() *ProbePolicies {
	if in == nil {
		return nil
	}
	out := new(ProbePolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePolicies) DeepCopyInto(out *ResourcePolicies) {
	*out = *in
	if in.DefaultResourceLimits != nil {
		in, out := &in.DefaultResourceLimits, &out.DefaultResourceLimits
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.DefaultResourceRequests != nil {
		in, out := &in.DefaultResourceRequests, &out.DefaultResourceRequests
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.MaxResourceLimits != nil {
		in, out := &in.MaxResourceLimits, &out.MaxResourceLimits
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePolicies.
func (in *ResourcePolicies) DeepCopy() *ResourcePolicies {
	if in == nil {
		return nil
	}
	out := new(ResourcePolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityPolicies) DeepCopyInto(out *SecurityPolicies) {
	*out = *in
	if in.DefaultSecurityContext != nil {
		in, out := &in.DefaultSecurityContext, &out.DefaultSecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.RequiredCapabilities != nil {
		in, out := &in.RequiredCapabilities, &out.RequiredCapabilities
		*out = make([]corev1.Capability, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenCapabilities != nil {
		in, out := &in.ForbiddenCapabilities, &out.ForbiddenCapabilities
		*out = make([]corev1.Capability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityPolicies.
func (in *SecurityPolicies) DeepCopy() *SecurityPolicies {
	if in == nil {
		return nil
	}
	out := new(SecurityPolicies)
	in.DeepCopyInto(out)
	return out
}
